# =========================
# Jenkins Server Setup Role
# =========================

# 1️⃣ Update system and install base packages
- name: Remove old Trivy repository if exists
  file:
    path: /etc/apt/sources.list.d/trivy.list
    state: absent
  become: yes

- name: Wait for apt to be available
  shell: while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done
  args:
    executable: /bin/bash
  become: yes

- name: Update system packages
  apt:
    update_cache: yes
    upgrade: yes
  become: yes
  retries: 3
  delay: 5
  register: apt_update
  until: apt_update is success

- name: Install required dependencies
  apt:
    name:
      - curl
      - wget
      - unzip
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
  become: yes

# 2️⃣ Install Docker
- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
  become: yes

# 3️⃣ Install AWS CLI v2
- name: Check if AWS CLI is installed
  command: aws --version
  register: aws_cli_check
  ignore_errors: yes
  changed_when: false

- name: Install AWS CLI v2
  when: aws_cli_check.rc != 0
  shell: |
    cd /tmp
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip -o awscliv2.zip
    ./aws/install
  args:
    executable: /bin/bash
  become: yes

# 4️⃣ Install Jenkins (manual method)
- name: Add Jenkins key and repo
  shell: |
    curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee \
      /usr/share/keyrings/jenkins-keyring.asc > /dev/null
    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
      https://pkg.jenkins.io/debian-stable binary/ | tee \
      /etc/apt/sources.list.d/jenkins.list > /dev/null
  args:
    executable: /bin/bash
  become: yes

- name: Update apt cache for Jenkins
  apt:
    update_cache: yes
  become: yes
  retries: 3
  delay: 5
  register: apt_update_jenkins
  until: apt_update_jenkins is success

- name: Install Java and Jenkins
  apt:
    name:
      - openjdk-17-jdk
      - jenkins
    state: present
  become: yes

- name: Enable and start Jenkins service
  systemd:
    name: jenkins
    enabled: yes
    state: started
  become: yes

# 5️⃣ Install Trivy (official script, works on all Ubuntu versions)
- name: Ensure /usr/local/bin exists
  file:
    path: /usr/local/bin
    state: directory
    mode: '0755'
  become: yes

- name: Install Trivy using official installer script
  shell: |
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  args:
    executable: /bin/bash
    creates: /usr/local/bin/trivy
  become: yes

- name: Verify Trivy installation
  command: trivy --version
  register: trivy_version
  changed_when: false
  become: yes
